[package]
name = "rayon"
# Reminder to update html_rool_url in lib.rs when updating version
version = "1.1.0"
authors = ["Niko Matsakis <niko@alum.mit.edu>",
           "Josh Stone <cuviper@gmail.com>"]
description = "Simple work-stealing parallelism for Rust"
license = "Apache-2.0/MIT"
repository = "https://github.com/rayon-rs/rayon"
documentation = "https://docs.rs/rayon/"
readme = "README.md"
keywords = ["parallel", "thread", "concurrency", "join", "performance"]
categories = ["concurrency"]
exclude = ["/ci/*", "/scripts/*", "/.travis.yml", "/appveyor.yml", "/bors.toml"]
publish = false

[workspace]
members = ["rayon-demo", "rayon-core", "rayon-futures"]
exclude = ["ci"]

[features]
use-debra = ["rayon-core/use-debra", "crossbeam-deque-reclaim"]
use-hazptr = ["rayon-core/use-hazptr", "crossbeam-deque-reclaim/use-hazptr"]

[dependencies]
rayon-core = { version = "1.5.0", path = "./rayon-core" }
crossbeam-deque-epoch = { package = "crossbeam-deque", version = "0.7.1" }
crossbeam-deque-reclaim = { package = "crossbeam-deque", path = "./crossbeam-deque", optional = true }

# This is a public dependency!
[dependencies.either]
version = "1.0"
default-features = false

[dev-dependencies]
docopt = "1"
lazy_static = "1"
rand = "0.6"
rand_xorshift = "0.1"
serde = "1"
serde_derive = "1"
doc-comment = "0.3"

# for benchmarking
[profile.release]
lto = true
