[package]
name = "crossbeam-deque"
# When publishing a new version:
# - Update CHANGELOG.md
# - Update README.md
# - Create "crossbeam-deque-X.Y.Z" git tag
version = "0.7.1"
authors = ["The Crossbeam Project Developers"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/crossbeam-rs/crossbeam"
homepage = "https://github.com/crossbeam-rs/crossbeam/tree/master/crossbeam-deque"
documentation = "https://docs.rs/crossbeam-deque"
description = "Concurrent work-stealing deque"
keywords = ["chase-lev", "lock-free", "scheduler", "scheduling"]
categories = ["algorithms", "concurrency", "data-structures"]
build = "build.rs"

[features]
use-hazptr = ["hazptr"]

[dependencies]
debra = { git = "https://github.com/oliver-giersch/debra" }
hazptr = { git = "https://github.com/oliver-giersch/hazptr", optional = true }

[dependencies.crossbeam-utils]
version = "0.6.5"

[dev-dependencies]
rand = "0.6"
